services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./milvus/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - default

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ./milvus/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - default

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.2
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ./milvus/volumes/milvus:/var/lib/milvus
      - ./milvus/milvus.yaml:/milvus/configs/milvus.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "${MILVUS_PORT}:${MILVUS_PORT}"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    networks:
      - default

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - WIKIART_COLLECTION=${WIKIART_COLLECTION}
      - BEST_ARTWORKS_COLLECTION=${BEST_ARTWORKS_COLLECTION}
      - CELEBAHQ_COLLECTION=${CELEBAHQ_COLLECTION}
      - MILVUS_IP=milvus-standalone
      - MILVUS_PORT=${MILVUS_PORT}
    volumes:
      - ./backend/src:/code/src
      - ../best_artworks:/best_artworks
      - ../wikiart:/wikiart
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - "standalone"
    networks:
      - default

  frontend:
    container_name: frontend
    build:
      context: ./frontend/docker
      dockerfile: Dockerfile
    volumes:
      - ./frontend/build:/build
    ports:
      - "3000:3000"
    networks:
      - default

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - DOLLAR=$
    volumes:
      - ./frontend/build:/frontend/build
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ../best_artworks:/usr/share/nginx/best_artworks
      - ../wikiart:/usr/share/nginx/wikiart
    ports:
      - "80:80"
    depends_on:
      - "backend"
    networks:
      - default

networks:
  default:
    name: image-viz
